name: eleven_flower_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  intl: ^0.20.2
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Pastikan folder 'assets' ada di luar folder 'lib', sejajar dengan pubspec.yaml
  assets:
    - assets/images/
    - assets/images/categori/
    
  # SAYA MATIKAN DULU BAGIAN FONT AGAR BISA DI-RUN
  # Nanti kalau sudah download file .ttf nya, baru tanda pagar '#' dihapus
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #   - family: Times New Roman
  #     fonts:
  #       - asset: assets/fonts/TimesNewRoman.ttf